pipeline {
    agent{
        docker {
            image 'node'
            args '-p 3000:300'
        }
    }

    stages {
        stage('Build') {
            steps{
                sh 'npm install'
            }
        }

    stage('Serve') {
        steps{
            sh 'npm start'
        }
    }
}

}